site_name: ROME

theme:
  name: material
  font: false

extra_css:
  - style.css

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'Home': 'index.md'
  - 'Getting started':
    - 'Installation': 'rome/getting-started/installation.md'
    - 'Create feed': 'rome/getting-started/create-feed.md'
    - 'Read feed': 'rome/getting-started/read-feed.md'
    - 'Convert feed': 'rome/getting-started/convert-feed.md'
    - 'Aggregate feeds': 'rome/getting-started/aggregate-feeds.md'
    - 'Register additional date formats': 'rome/getting-started/register-additional-datetime-formats.md'
    - 'Preserve WireFeed': 'rome/getting-started/preserve-wirefeed.md'
    - 'Create a custom module': 'rome/getting-started/custom-module.md'
  - 'Technical Documentation':
    - 'Bean Utilities': 'rome/technical-docs/bean-utilities.md'
    - 'CopyFrom interface': 'rome/technical-docs/copyfrom-interface.md'
    - 'Date mapping': 'rome/technical-docs/date-mapping.md'
    - 'Encoding detection': 'rome/technical-docs/encoding-detection.md'
    - 'Feed parsing': 'rome/technical-docs/feed-parsing.md'
    - 'OSGi': 'rome/technical-docs/osgi.md'
    - 'Plugin Mechanism': 'rome/technical-docs/plugin-mechanism.md'
    - 'URI Mapping': 'rome/technical-docs/uri-mapping.md'
  - 'ROME Certiorem':
    - 'Introduction': 'rome-certiorem/index.md'
    - 'Getting started': 'rome-certiorem/getting-started.md'
  - 'ROME Fetcher': 'rome-fetcher/index.md'
  - 'ROME Modules':
    - 'Overview': 'rome-modules/index.md'
    - 'A9 OpenSearch': 'rome-modules/a9-opensearch.md'
    - 'Content': 'rome-modules/content.md'
    - 'Creative Commons': 'rome-modules/creative-commons.md'
    - 'GeoRSS': 'rome-modules/georss.md'
    - 'Google Base': 'rome-modules/google-base.md'
    - 'iPhoto Photocasting': 'rome-modules/iphoto-photocasting.md'
    - 'iTunes Podcasting': 'rome-modules/itunes-podcasting.md'
    - 'Microsoft Simple List Extensions': 'rome-modules/microsoft-simple-list-extensions.md'
    - 'Microsoft Simple Sharing Extensions': 'rome-modules/microsoft-simple-sharing-extensions.md'
    - 'Slash': 'rome-modules/slash.md'
    - 'Yahoo! MediaRSS': 'rome-modules/yahoo-mediarss.md'
    - 'Yahoo! Weather': 'rome-modules/yahoo-weather.md'
  - 'ROME OPML': 'rome-opml/index.md'
  - 'ROME Propono': 'rome-propono/index.md'
  - 'FAQ': 'faq.md'
